### ISSUE TITLE
Switching windows crashes game

### ISSUE THREAD

**Issue by nelsonxb** [nelsonxb/GraphPaperRaceGame#9]
It is known that switching windows while playing causes a crash on Linux running with recent XOrg.

This is a problem with LWJGL and/or XOrg. It appears to be related to another error in XOrg affecting other (non-java) applications (e.g. ValveSoftware/steam-for-linux#3364) (`_xgeWireToEvent: Unknown extension 148, this should never happen.`, the error message mentions `request_code: 148`).

**This is not an error in the game itself**, but (probably) in XOrg or LWJGL. This issue indicates that **we are aware of the problem**.

**Comment by nelsonxb** [comment]
Stack trace:

```
_xgeWireToEvent: Unknown extension 148, this should never happen.
_xgeWireToEvent: Unknown extension 148, this should never happen.
_xgeWireToEvent: Unknown extension 148, this should never happen.
Exception in thread "main" org.lwjgl.LWJGLException: X Error - disp: 0x6d0a6b70 serial: 311 error: BadMatch (invalid parameter attributes) request_code: 148 minor_code: 1
    at org.lwjgl.opengl.LinuxDisplay.globalErrorHandler(LinuxDisplay.java:321)
    at org.lwjgl.opengl.LinuxEvent.getPending(Native Method)
    at org.lwjgl.opengl.LinuxDisplay.processEvents(LinuxDisplay.java:850)
    at org.lwjgl.opengl.LinuxDisplay.update(LinuxDisplay.java:912)
    at org.lwjgl.opengl.Display.processMessages(Display.java:600)
    at org.lwjgl.opengl.Display.update(Display.java:666)
    at org.lwjgl.opengl.Display.update(Display.java:628)
    at org.newdawn.slick.AppGameContainer.gameLoop(AppGameContainer.java:421)
    at org.newdawn.slick.AppGameContainer.start(AppGameContainer.java:321)
    at org.newdawn.slick.AppGameContainer$start.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
    at io.github.nelsoncrosby.gsui.TestGame.main(TestGame.groovy:64)
```

**Comment by nelsonxb** [comment]
This is actually **_NOT_** an LWJGL issue, but a Slick2D issue. As the main Slick2D branch is stale, it is **_unlikely to ever be fixed_**. The only possibility for fixing would be to move away from Slick2D (#29). My tests with libGDX (another LWJGL-based framework) had no such issues.
